### ISSUE TITLE
오타 제보 합니다.

### ISSUE THREAD

**Issue by Kwakcena** [depromeet/8th-final-3team-front#1]
프로젝트 잘 봤습니다.  오타가 있어서 제보 드려요

`Home.tsx` 컴포넌트에서 주소 검색 부분에 '검새 중...' -> '검색 중...'

**Comment by minkukjo** [comment]
@Kwakcena 
안녕하세요 이슈 올려주신게 1월인데 이제서야 확인을 했네요. 
부족한 프로젝트였는데 잘봐주셔서 감사합니다. 
수정하도록 하겠습니다. 이슈 제보 감사드립니다!
